[package]
name = "simulation"
version = "0.0.0"
authors = ["Matthias Fauconneau <matthias.fauconneau@gmail.com>"]
edition = "2018"
links = "umfpack"

[build-dependencies]
bindgen = ""

[dependencies]
framework = { path = "framework", features = ["const_fn","array","window","color_sRGB","thread"] }
